CREATE TABLE "Users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Gender" vanchar,
  "Age" integer,
  "Name" vanchar NOT NULL,
  "Email" vanchar NOT NULL,
  "password" vanchar,
  "Phone_number" integer,
  "Image" url NOT NULL,
  "Note" text,
  "Created_at" timestamp,
  "admin" bool DEFAULT 0
);

CREATE TABLE "Level" (
  "user_id" int PRIMARY KEY,
  "Badminton" integer DEFAULT 0,
  "Basketball" integer DEFAULT 0,
  "Volleyball" integer DEFAULT 0
);

CREATE TABLE "Order_info" (
  "reservation_id" integer,
  "user_id" int,
  "read" bool DEFAULT 0,
  PRIMARY KEY ("reservation_id", "user_id")
);

CREATE TABLE "Stadiums" (
  "stadium_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "price" integer NOT NULL,
  "max_capacity" increment NOT NULL,
  "availble" bool NOT NULL,
  "picture" vanchar DEFAULT 'http://test.com',
  "admin_id" int NOT NULL,
  "rule" text
);

CREATE TABLE "TimeSlots" (
  "timeslot_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "start_time" TIME NOT NULL,
  "end_time" TIME NOT NULL
);

CREATE TABLE "Activity" (
  "reservation_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "stadium_id" int NOT NULL,
  "timeslot" int,
  "note" vanchar,
  "host_id" int,
  "max" int NOT NULL
);

CREATE TABLE "Feedback" (
  "feedback_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reservation_id" int,
  "stadium_id" int,
  "read" bool DEFAULT 0,
  "suggestion" vanchar
);

CREATE TABLE "Equipments" (
  "stadium_id" int PRIMARY KEY,
  "water_faucet" bool DEFAULT 0,
  "bathroom" bool DEFAULT 0,
  "air_con" bool DEFAULT 0,
  "vending" bool DEFAULT 0
);

ALTER TABLE "Level" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Order_info" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Activity" ADD FOREIGN KEY ("reservation_id") REFERENCES "Order_info" ("reservation_id");

ALTER TABLE "Activity" ADD FOREIGN KEY ("stadium_id") REFERENCES "Stadiums" ("stadium_id");

ALTER TABLE "Activity" ADD FOREIGN KEY ("timeslot") REFERENCES "TimeSlots" ("timeslot_id");

ALTER TABLE "Feedback" ADD FOREIGN KEY ("reservation_id") REFERENCES "Activity" ("reservation_id");

ALTER TABLE "Feedback" ADD FOREIGN KEY ("stadium_id") REFERENCES "Stadiums" ("stadium_id");

ALTER TABLE "Equipments" ADD FOREIGN KEY ("stadium_id") REFERENCES "Stadiums" ("stadium_id");

ALTER TABLE "Activity" ADD FOREIGN KEY ("host_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Users" ADD FOREIGN KEY ("user_id") REFERENCES "Stadiums" ("admin_id");
