name: Docker CD to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
            git clone https://github.com/gino79445/Stadium-Matching-System.git
            cd Stadium-Matching-System
            mkdir nginx
            touch ./nginx/cert.crt
            touch ./nginx/cert.key
            touch ./nginx/nginx.conf
            echo ${{ secrets.CERT }} >> ./nginx/cert.crt
            echo ${{ secrets.PRIVATE_KEY }} >> ./nginx/cert.key
            echo ${{ secrets.NGINX }} >> ./nginx/nginx.conf
            echo ${{ secrets.ENV }} >> .env
            sudo docker-compose up -d --build

